### ISSUE TITLE
Add fee calculations and explanation

### ISSUE THREAD

**Issue by rishkwal** [citadel-tech/Coinswap-Protocol-Specification#6]
The fee documentation needs more details. A few things that are needed to be added:
- Calculation Formulas of different fees
- A section on mining fees

Maybe adding an example of a all the fees in a complete swap would be useful as well.

**Comment by mojoX911** [comment]
@KnowWhoami  Are you taking it up?

**Comment by KnowWhoami** [comment]
Yes, I am working on it.
